In [25]:
import numpy as np
import math as mt

In [7]:
#Selection Sort

In [8]:
def selection_sort(vector):
    for i in range(0, len(vector)):
        for j in range(i+1, len(vector)):
            if vector[j] < vector[i]:
                aux = vector[j]
                vector[j] = vector[i]
                vector[i] = aux
    print("Selection",vector)

In [9]:
#Insertion Sort

In [10]:
def insection_sort(vector):
    for i in range(1,len(vector)):
        valorAtual = vector[i]
        k = i
        while k > 0 and vector[k-1] > valorAtual:
            vector[k] = vector[k-1]
            k -= 1

        vector[k] = valorAtual
    print("Insection",vector)

In [11]:
#Merge Sort

In [12]:
def M_sort(vector):
    print("Splitting ",vector)
    if len(vector)>1:
        mid = len(vector)//2
        lefthalf = vector[:mid]
        righthalf = vector[mid:]

        merge_sort(lefthalf)
        merge_sort(righthalf)

        i=0
        j=0
        k=0
        while i < len(lefthalf) and j < len(righthalf):
            if lefthalf[i] < righthalf[j]:
                vector[k]=lefthalf[i]
                i=i+1
            else:
                vector[k]=righthalf[j]
                j=j+1
            k=k+1
        # Merging é uma operação linear
        while i < len(lefthalf):
            vector[k]=lefthalf[i]
            i=i+1
            k=k+1

        while j < len(righthalf):
            vector[k]=righthalf[j]
            j=j+1
            k=k+1
    print("Merging",vector)

In [ ]:
#Merge Sort 2.0

In [89]:
# Merges 2 Subarrays ( v[left..mid] and v[mid+1..right])
def merge(v,left,mid,right):
    p1 = mid - left + 1
    p2 = right - mid
    
    # Temp arrays
    L_temp = [0] * (p1)
    R_temp = [0] * (p2)
    
    # Copy data to temp arrays L[] and R[]
    for i in range(0, p1):
        L_temp[i] = v[left + i]
    for j in range(0, p2):
        R_temp[j] = v[mid + 1 + j]
    
    # Merge the temp arrays back into v[left...right]
    i = 0 # ( Initial index of first subarray)
    j = 0 # ( Initial index of the second subarray)
    k = left # (initial index of the merged subarray)
    
    while i < p1 and j < p2:
        if L_temp[i] <= R_temp[j]:
            v[k] = L_temp[i]
            i += 1
        else:
            v[k] = R_temp[j]
            j += 1
        k += 1
        
    # Copy the remaining elements (if there are any)
    while i < p1:
        v[k] = L_temp[i]
        i += 1
        k += 1
    while j < p2:
        v[k] = R_temp[j]
        j += 1
        k += 1   
    

In [96]:
def mergeSort(v, left, right):
    if left < right:
        mid = mt.ceil((left + (right - 1))/2) # Avoids overflow
        
        mergeSort(v, left, mid)
        mergeSort(v, mid + 1, right)
        merge(v, left, mid, right)
        print(v)

In [101]:
#Quick Sort

In [112]:
def partition(v,l,r):
    pivot = v[r]
    start = l - 1
    end = r
    
    done = 0
    while not done:
        while not done:
            start = start + 1
            
            if start == end:
                break
            if v[start] > pivot:
                v[end] = v[start]
                break
        while not done:
            end = end - 1
            
            if end == start:
                done = 1
                break
            if v[end] < pivot:
                v[start] = v[end]
                break
    v[end] = pivot
    return end

In [119]:
def quickSort(v,l,r):
    if l < r: 
        split = partition(v,l,r)
        quickSort(v, l, split-1)
        quickSort(v, split + 1, r)
    else: 
        return v
    #if
        

In [114]:
#Heap Sort( Selection Otimizado )

In [115]:
vector = np.array([3,76,34,12,-4,-45,27,44,2,11,10])
insection_sort(vector)

Insection [-45  -4   2   3  10  11  12  27  34  44  76]


In [116]:
vector = np.array([3,76,34,12,-4,-45,27,44,2,11,10])
selection_sort(vector)

Selection [-45  -4   2   3  10  11  12  27  34  44  76]


In [117]:
vector = np.array([3,76,34,12,-4,-45,27,44,2,11,10])
n = len(vector)
mergeSort(vector, 0, n-1)

[  3  76  34  12  -4 -45  27  44   2  11  10]
[  3  34  76  12  -4 -45  27  44   2  11  10]
[  3  34  76  -4  12 -45  27  44   2  11  10]
[  3  34  76 -45  -4  12  27  44   2  11  10]
[-45  -4   3  12  34  76  27  44   2  11  10]
[-45  -4   3  12  34  76  27  44   2  11  10]
[-45  -4   3  12  34  76   2  27  44  11  10]
[-45  -4   3  12  34  76   2  27  44  10  11]
[-45  -4   3  12  34  76   2  10  11  27  44]
[-45  -4   2   3  10  11  12  27  34  44  76]


In [118]:
vector = np.array([3,76,34,12,-4,-45,27,44,2,11,10])
n = len(vector)
quickSort(vector, 0, n-1)

IndexError: index 11 is out of bounds for axis 0 with size 11